### PR TITLE
Add NOTES.test-0.18

### PR DESCRIPTION
**Pull request by taldcroft**
This is a rough first draft.  Many of the test details are wrong, to be fixed by subsequent commits to this branch in testing.

### CODE REVIEW

**Comment by taldcroft** [comment]
This is to be merged only after skare-0.18 is fully installed and tested.

**Comment by jeanconn** [comment]
For testing starcheck, now that the xija model in it depends on ENG_ARCHIVE
and cmd_states,

1) should our test run for record include something newer than the AUG0104
test (that doesn't actually call the model)?

2) is there a recommended testing method to provide access to cmd_states.h5?

(in my previous local testing, I just did the $SKA/data/cmd_states link
thing)

**Comment by taldcroft** [comment]
> 1) should our test run for record include something newer than the AUG0104 test (that doesn't actually call the model)?

That would make sense.

> 2) is there a recommended testing method to provide access to cmd_states.h5?

Can we simply copy it to /proj/sot/ska/dev/data/cmd_states?  We should use the data link only if we run into a roadblock doing things with copies.

**Comment by jeanconn** [comment]
> Can we simply copy it to /proj/sot/ska/dev/data/cmd_states? We should use
> the data link only if we run into a roadblock doing things with copies.
>

That would be fine.  I just couldn't recall if SKA/data will get sync'd
over to GRETA and if so if it would cause a problem after testing.

**Comment by taldcroft** [comment]
Only flight data in `/proj/sot/ska/data/..` on HEAD gets synced to the like-named directories on GRETA.  Over on GRETA there actually is a link from `test/data` => `../data`  (test => flight) because in this case `test` is actually production.

**Comment by jeanconn** [comment]
These test failures do not appear to be regressions (fail with flight ska), but perhaps should be fixed.
 
 - [ ] 32 bit asciitable
 - [ ] Ska.ftp
 - [ ] Ska.quatutil

I haven't been able to reproduce the failure on "ipython --pylab=qt" on kadi just yet.

**Comment by jeanconn** [comment]
I thought the Ska.quatutil nosetest error was not a regression, because the variable values were the same at the point of error as in the flight version of the code, but it looks like the numpy behavior here has changed and the errors look real and need to be fixed:

ska
```
ipdb> ra = np.array([1], dtype=np.float64)[0]
ipdb> ok = False
ipdb> ra[ok]
*** IndexError: invalid index to scalar variable.
```

dev
```
ipdb> ra = np.array([1], dtype=np.float64)[0]
ipdb> ok = False
ipdb> ra[ok]
array([], dtype=float64)
ipdb> ra[ok] += 360
*** TypeError: 'numpy.float64' object does not support item assignment
```

**Pull request merged**
