### PR TITLE
Hdf5 1.8.7

### PR DESCRIPTION
**Pull request by jeanconn**
Use a source build of hdf5 1.8.7 instead of a conda-provided version

### CODE REVIEW

**Comment by jeanconn** [comment]
There was a built conda package for hdf5 1.8.9, but I could not immediately tell from the release notes if that was ABI compatible with the matlab 1.8.6 version, so this PR uses the source built 1.8.7 from skare 0.17.

**Comment by taldcroft** [comment]
This looks right to me, clear to proceed with a test build if you haven't already.  It appears that /proj/sot/ska/dev is currently misconfigured (wrong versions of IPython, pytables).

**Comment by jeanconn** [comment]
>  It appears that /proj/sot/ska/dev is currently misconfigured (wrong
> versions of IPython, pytables).
>
Could this just be the situation that you were testing on a CentOS6 machine
before I'd made the arch link?

**Comment by taldcroft** [comment]
Yup.  I now confirmed tests for eng_archive, kadi, and xija are passing on CentOS6.

BTW, I tried to build myself locally on kadi and got an error on git (maybe related to git-gui) that I pushed through.   Are you able to get a clean build of that?

**Comment by jeanconn** [comment]
I got no errors errors that stopped the build on unagi.  I would assume that the git build is "discovering" some other lib on kadi and trying to use it.

**Comment by taldcroft** [comment]
So are you going to push this up to GRETA?  BTW, on GRETA it is acceptable (and probably preferred) to just link ska/dev/data => ska/data and ska/dev/share => ska/share.  That tests the eventual configuration for `test` and `flight`.

**Comment by jeanconn** [comment]
Sure.​

I haven't actually done one of these pushes so I might as well get the
practice if we are going to do this a dozen times...

I was planning to merge or rebase this PR first and get the git-rev right
before pushing.

**Comment by taldcroft** [comment]
I usually rsync to a directory in /proj/sot/ska/tmp/ and then mv.

**Comment by taldcroft** [comment]
For the record, something like:
```
rsync -av --exclude=/dev/build \
    --exclude=/dev/data --exclude=/dev/share \  # MAYBE, see below
   user@ccosmos:/proj/sot/ska/dev /proj/sot/ska/tmp/

# mv it into place
cd /proj/sot/ska/dev
ln -s ../data
ln -s ../share
```
Now we have the issue that some files in `share` may be different in this release than in the current flight.  This probably only affects starcheck since the other ones there should just be launchers that aren't different.  Anyway, something to think about.

**Comment by jeanconn** [comment]
Should group pegasus have write permission here?  Or should the files be
group ska?  Or should they be group ska and still not writeable by group?

**Comment by jeanconn** [comment]
​Also, since I haven't moved starcheck.pl into share, starcheck has no
files in share to worry about.

**Comment by taldcroft** [comment]
No, pegasus should not have write perm.  I never worry about group in this case, these files are owned and managed by SOT exclusively.

**Comment by jeanconn** [comment]
Pegasus has write perm by default with "-a" in rsync, right?  I'll chmod
g-w when this is all done.

**Comment by jeanconn** [comment]
Oh.  I hadn't absorbed that you pulled all the libs in the anaconda build.
PGPLOT now broken on GRETA because libg2c install removed.​

**Pull request merged**
