### PR TITLE
Update startup 10_define_impska.py to use modern API

### PR DESCRIPTION
**Pull request by taldcroft**
This updates the startup template file `10_define_impska.py` to use the modern IPython API for doing this.  It is compatible with the current flight Ska IPython.

Testing: I have had this in my `profile_default/startup` since working on the Py3 branch.

### CODE REVIEW

**Comment by taldcroft** [comment]
The driver being to remove one file diff from the py3 branch.

**Comment by jeanconn** [comment]
I confess I don't use these magics so I'm a lousy reviewer for this ... but I also don't have any potential conflict :smirk: .

**Comment by jeanconn** [comment]
This looks merged but not installed in HEAD flight 64.  Do you want it installed @taldcroft ?

**Comment by taldcroft** [comment]
Yes please.

**Comment by jeanconn** [comment]
Oops, forgot to acknowledge.  Done.

**Pull request merged**
