### PR TITLE
Install git via conda instead of from source build

### PR DESCRIPTION
**Pull request by jeanconn**
Install Py3 git via conda instead of from source build

### CODE REVIEW

**Comment by jeanconn** [comment]
This doesn't need to be a Py3 ony-change *and* appears a little broken (https support?), so closing this unmerged for now.

**Comment by taldcroft** [comment]
I thought our home-built git had the same https problem?
```
ska-kadi$ git clone https://github.com/sot/skare.git
Cloning into 'skare'...
fatal: Unable to find remote helper for 'https'
```

**Comment by jeanconn** [comment]
Right, that's why I called it a just "little broken".  You are right that it doesn't look like a regression.
I just think there's bound to be a conda combination that gets it right though.

In the meantime, https might not be the right default for testr.

https://github.com/sot/testr/blob/effcfd377723b0e9808da87751baa49a55a349b9/testr/packages.py#L63

**Comment by taldcroft** [comment]
Generally this is finessed by using /usr/bin/git where available (https://github.com/sot/ska_testr/blob/master/packages/Ska.Table/test_unit_git.sh#L1).  But this will fail on GRETA...

**Comment by jeanconn** [comment]
And fails right now on quango and presto (presto can probably be fixed).

I haven't tried; does `packages_repo` support just a directory for GRETA?

**Comment by taldcroft** [comment]
> I haven't tried; does packages_repo support just a directory for GRETA?

It should and that was something I had in mind.

**Pull request closed without merging**
