### PR TITLE
Add Crypt::SSLeay

### PR DESCRIPTION
**Pull request by jeanconn**
Add Crypt::SSLeay to support https URLs.

This is largely for https support in LWP::UserAgent for Replan Central.

### CODE REVIEW

**Comment by jeanconn** [comment]
More testing to-do, but it looks like by grabbing this old version of Crypt::SSLeay we can avoid the need to pull in a bunch of more modern dependencies.

**Comment by jeanconn** [comment]
I note that the old version of Crypt::SSLeay doesn't seem to have a Makefile.PL option to skip asking about doing the live tests, so this is not a completely non-interactive install.  I don't think we care (both because this is Perl and because should be very near the end of a full 'make all_xx')

**Comment by jeanconn** [comment]
Testing lookgs good.

I set up a new dev ska in /data/fido/pska with the new Crypt::SSLeay installed.  I then used this very simple test code in both this new dev ska and flight ska:

```
#!/usr/bin/env perl

use strict;
use warnings;
use LWP::UserAgent;

my $user = 'xxxxxxx';
my $password = 'xxxxxxx';

my $ua = LWP::UserAgent->new(ssl_opts => { verify_hostname => 1});;
$ua->timeout(120);
my $url= "https://occweb.cfa.harvard.edu/occweb/web/occindex.htm";
my $request = new HTTP::Request('GET', $url);
$request->authorization_basic($user, $password);
my $response = $ua->request($request);
my $content = $response->content();
print $content;
```

devska prints out the page.  flight ska prints

```
LWP will support https URLs if the Crypt::SSLeay module is installed.
More information at <http://www.linpro.no/lwp/libwww-perl/README.SSL>.
```

I then installed an https-config version of arc in the new dev ska and in my old dev ska.  Changes include

```
fido: git diff
diff --git a/iFOT_queries.cfg b/iFOT_queries.cfg
index a959b3c..e3bbd2d 100644
--- a/iFOT_queries.cfg
+++ b/iFOT_queries.cfg
@@ -7,7 +7,7 @@ timeout = 120          # Timeout for queries to iFOT (seconds)
 
 # Default query params.  These can be overridden within a specific query
 <default>
- http    = http://occweb.cfa.harvard.edu/occweb/web/webapps/ifot/ifot.php
+ http    = https://occweb.cfa.harvard.edu/occweb/web/webapps/ifot/ifot.php
  r       = home
  t       = builder
  a       = show
diff --git a/web_content.cfg b/web_content.cfg
index 4a0205b..48b985e 100644
--- a/web_content.cfg
+++ b/web_content.cfg
@@ -5,7 +5,7 @@
 </acis_ace>
 
 <orbit_image>
-  url = http://occweb.cfa.harvard.edu/occweb/web/webapps/ifot/ifot.php?r=home&t=qserver&format=orbit&detail=properties&fg=000000
+  url = https://occweb.cfa.harvard.edu/occweb/web/webapps/ifot/ifot.php?r=home&t=qserver&format=orbit&detail=properties&fg=00000
   add_tstart_tstop = 1
   auth_file = /proj/sot/ska/data/aspect_authorization/occweb-*
   <content orbit>
```

New Crypt::SSLeay devska output from get_iFOT_events and get_web_content:
```
fido: /data/fido/pska/bin/get_iFOT_events.pl 
fido: /data/fido/pska/bin/get_web_content.pl 
```
And a `chandra_orbit.png` exists and the content in `iFOT_events` looks reasonable.

Old devska output
```
dska-fido: /data/fido/ska/bin/get_iFOT_events.pl 
Use of uninitialized value in subroutine entry at /data/fido/ska/bin/get_iFOT_events.pl line 103.
Use of uninitialized value in subroutine entry at /data/fido/ska/bin/get_iFOT_events.pl line 103.
Use of uninitialized value in subroutine entry at /data/fido/ska/bin/get_iFOT_events.pl line 103.
Use of uninitialized value in subroutine entry at /data/fido/ska/bin/get_iFOT_events.pl line 103.
Use of uninitialized value in subroutine entry at /data/fido/ska/bin/get_iFOT_events.pl line 103.
Use of uninitialized value in subroutine entry at /data/fido/ska/bin/get_iFOT_events.pl line 103.
Use of uninitialized value in subroutine entry at /data/fido/ska/bin/get_iFOT_events.pl line 103.
Use of uninitialized value in subroutine entry at /data/fido/ska/bin/get_iFOT_events.pl line 103.
Use of uninitialized value in subroutine entry at /data/fido/ska/bin/get_iFOT_events.pl line 103.
Use of uninitialized value in subroutine entry at /data/fido/ska/bin/get_iFOT_events.pl line 103.
Use of uninitialized value in subroutine entry at /data/fido/ska/bin/get_iFOT_events.pl line 103.
dska-fido: /data/fido/ska/bin/get
get_iFOT_events.pl* get_web_content.pl* 
dska-fido: /data/fido/ska/bin/get_web_content.pl 
Warning: 501 Protocol scheme 'https' is not supported (Crypt::SSLeay not installed) for web data orbit_image (https://occweb.cfa.harvard.edu/occweb/web/webapps/ifot/ifot.php?r=home&t=qserver&format=orbit&detail=properties&fg=000000&bg=F0F1FF&size=300x230&scale=1400&showtimes=false&border=false&ul=6&tstart=2017:026:15:10:33.000&tstop=2017:029:06:40:33.000)
```

And there is no iFOT_events directory and no `chandra_orbit.png`

**Comment by jeanconn** [comment]
I don't see how adding the module can *break* anything that worked before.

**Comment by jeanconn** [comment]
Do we even need a release for this?  I thought our add-a-package routine was pretty much just to push the PR and install.

**Comment by taldcroft** [comment]
Correct, good to install.

**Comment by jeanconn** [comment]
So, capturing our phone call for this record: the only thing that I really couldn't test was if a redirected URL will be handled the same as an actual HTTPS URL on these fetches done by both by Python and Perl.  So, if the transition breaks anything, our likely strategy (as just mentioned on the phone) would be to then update the URLs in arc and kadi to be HTTPS.

**Pull request merged**
