### PR TITLE
Add python packages to support saving jpegs

### PR DESCRIPTION
**Pull request by jeanconn**
Add python packages to support saving jpegs

### CODE REVIEW

**Comment by jeanconn** [comment]
Install from pkgs.conda of these packages has not been tested.

**Comment by taldcroft** [comment]
Going forward I was pondering having a `pinned` file and using `conda update --all`.  The one thing I discovered in testing this is that this can (and does) allow for new build versions at the same package version.  I guess we aren't supposed to care, but ...

**Comment by taldcroft** [comment]
Though as I think about it I'm not sure there is any benefit to that strategy over `conda install --file pkgs.conda`.  Annoyingly enough a file for `install` requires an `=` equal sign while the pinned file requires a space between package and version.  They really need to settle on something there...

I just tried `conda install` and it gives the same result as using the pinned file.

**Comment by taldcroft** [comment]
Anyway :+1: on this for merge.

**Comment by jeanconn** [comment]
And yes, I was annoyed at the different package spec in the export file vs the pinned file, which is why I  backed off of pushing for the pinned file for the time being.  It probably will be helpful in the full conda skare.

**Pull request merged**
