### PR TITLE
GRETA update for MATLAB Tools release 2016_210

### PR DESCRIPTION
**Pull request by jeanconn**
Python 2.7.12 GRETA update for aimpoint update

### CODE REVIEW

**Comment by jeanconn** [comment]
Should I include starcheck or just commit to supporting it in GRETA test?

**Comment by jeanconn** [comment]
Also note that this is a PR against the new "greta" branch which has up through 0.18-r542-f3fe1d4.

**Comment by taldcroft** [comment]
I don't think we need to have starcheck in GRETA flight since it is difficult to keep fresh there.

**Comment by jeanconn** [comment]
OK.  That's fine.  I wondered about it since we have an outdated one there
already.  It probably makes sense to disable it at some point.

**Comment by jeanconn** [comment]
I'm going to delete the starcheck commit instead of "reverting" it with
another commit in this case.

**Comment by jeanconn** [comment]
Do we need any new tests for this sqlite update or are we covered enough in the kadi tests?

**Comment by jeanconn** [comment]
Also, should GRETA branch builds be fully tested on HEAD or can we skip to the GRETA tests.

**Comment by taldcroft** [comment]
They need to be tested prior to installation to flight on GRETA.  I think that implies testing on HEAD via your vbox, right?

**Comment by jeanconn** [comment]
In the past I've tested:

1) on the vbox as much as possible
2) again in HEAD /proj/sot/ska/dev
3) again as the official install on GRETA dev

and then we've run smoke tests after install to

4) flight GRETA

I'm thinking about skipping to testing on GRETA dev.

**Comment by jeanconn** [comment]
Actually, I suppose that's not true, I should separate out the dev testing from the flight testing.  So, dev testing has looked like:

1) vbox as much as possible
2) again in HEAD /proj/sot/ska/dev
3) again as the official install on GRETA dev

and flight testing has looked like

1) vbox as much as possible
2) again as the official install on GRETA flight.

In the dev testing, I think I can skill 1 and 2 safely.

**Comment by taldcroft** [comment]
> In the dev testing, I think I can skill 1 and 2 safely.

Agreed.

**Comment by jeanconn** [comment]
It looks like my dev build has a broken python-sybase installation (access to the /soft/SYBASE directory sometimes hiccups on the virtualbox).  I don't see this as a problem for the GRETA builds.

**Comment by jeanconn** [comment]
Merging this PR this way leaves the `greta` branch with a tip that does not match the sha of the installed release.  I think that is fine.

**Comment by taldcroft** [comment]
Yeah, that's fine.  Just be sure the release tag is correct.

**Comment by jeanconn** [comment]
Yes, that's all consistent at ca170c6 so I think we're good.

**Pull request merged**
