### PR TITLE
Reunification

### PR DESCRIPTION
**Pull request by jeanconn**
Reunify skare.

This is just an idea to pull apart Py2, Py3, and shared pieces of the install and create some new Makefile targets to make it easier to keep everything in one installable branch. The idea is messy but it might keep things more sane for the next few months.

### CODE REVIEW

**Comment by taldcroft** [comment]
Hmm, yes pretty messy.  I would propose focusing on unifying just `pkgs.manifest` enough so that any relevant PR / commits to master (Ska) can be cherry-picked to `py3`.  It might already be good enough?  Then just do that procedurally.

**Comment by jeanconn** [comment]
Fair enough.  To some extent, I think the separate `py3` branch is just "hiding" this inherent messiness and bringing everything top-level is a bit more manageable for my brain.  But no strong driver for this now.   It did let me immediately see what is working and not working if we float more packages in conda.  

I also think I like the idea it prompted to use conda-env export as the method to record a reproducible/installable conda packages list.  `conda list --explicit` can also work, but looks like it can be more confusing if there is a mismatch in original Miniconda files.

**Comment by taldcroft** [comment]
I like the `conda-env export` idea.

It would be interesting to try rebasing py3 on master at this point and possibly unify in that context first.  Then being able to see the diffs might allow some unification now.

**Comment by taldcroft** [comment]
We may come back to this someday, but baseline now is two branches, `master` and `py3`.  At some point this should become `master` and `py2`.

**Pull request closed without merging**
