### PR TITLE
Update to kadi 3.14.0

### PR DESCRIPTION
**Pull request by jeanconn**
Update to kadi 3.14.0 which includes the new break down of one shots per axis

### CODE REVIEW

**Comment by jeanconn** [comment]
This is not back-compatible, so really needs to be installed simultaneously on all platforms.  @taldcroft when do you think there's a good time for that?

**Comment by jeanconn** [comment]
It looks like this is forward compatible in just an aliveness check

```
In [3]: from kadi import paths
In [4]: paths.DATA_DIR()
Out[4]: '/home/jeanconn/git/kadi'
In [5]: from kadi import events
In [9]: ms = events.manvrs.filter(obsid=20078)
In [10]: ms[0].one_shot
Out[10]: 10.789809509760344
```

**Comment by taldcroft** [comment]
You might try running the self tests within IPython with flight kadi, with the KADI env var pointing to the directory with the new events db.  You might need to make sure there is a cmds db file available as well.

**Comment by taldcroft** [comment]
Looks like there is no testing of cmds.  :frowning:  We do need to beef up the kadi testing, but at least there is plenty of usage of `manvrs`.

**Comment by jeanconn** [comment]
Sure.  Self tests are fine too with the same setup (events.db3 is in ~/git/kadi).
```
In [4]: paths.DATA_DIR()
Out[4]: '/home/jeanconn/git/kadi'
In [7]: os.environ['SKA']
Out[7]: '/proj/sot/ska'
In [8]: kadi.__file__
Out[8]: '/proj/sot/ska/arch/x86_64-linux_CentOS-5/lib/python2.7/site-packages/kadi/__init__.pyc'
In [2]: kadi.test()
=================================================== test session starts ====================================================
platform linux2 -- Python 2.7.9 -- py-1.4.26 -- pytest-2.6.4
collected 15 items 

kadi/tests/test_events.py ..........
kadi/tests/test_occweb.py .....

================================================ 15 passed in 12.61 seconds ================================================
Out[2]: 0
```

**Comment by jeanconn** [comment]
I didn't immediately see a way to have kadi report the location of events.db3, but hopefully it is using the one in DATA_DIR.

**Comment by taldcroft** [comment]
You can print `paths.EVENTS_DB_PATH()`: https://github.com/sot/kadi/blob/master/kadi/paths.py#L12

**Comment by jeanconn** [comment]
Oops.  Thanks!  I must have used that earlier in my checking but missed it when tab completing today.

**Comment by jeanconn** [comment]
It looks like the "flight" database starts with maneuvers at '1999:231', but my attempt to follow the directions gives a database that goes back further with more maneuvers just labeled as 'interm_att'.  Will this cause any downstream issues @taldcroft ?

flight db
```
In [3]: events.manvrs.filter(start='1999:001', stop='2000:001')
Out[3]: 
<Manvr: start=1999:231:18:03:14.865 dur=2901 n_dwell=1 template=normal>
<Manvr: start=1999:232:00:00:10.191 dur=789 n_dwell=1 template=normal>
<Manvr: start=1999:232:02:02:39.441 dur=2757 n_dwell=1 template=normal>
```

new db
```
In [11]: events.manvrs.filter(start='1999:001', stop='2000:001')
Out[11]: 
<Manvr: start=1999:209:14:11:14.865 dur=1115 n_dwell=0 template=interm_att>
<Manvr: start=1999:209:15:51:16.240 dur=1550 n_dwell=0 template=interm_att>
<Manvr: start=1999:209:18:41:53.940 dur=558 n_dwell=0 template=interm_att>
<Manvr: start=1999:209:21:01:54.841 dur=558 n_dwell=0 template=interm_att>
<Manvr: start=1999:209:21:38:56.016 dur=1114 n_dwell=0 template=unknown>
```

**Comment by taldcroft** [comment]
That doesn't look good.  Unless we understand what these maneuvers actually are then I'm a little worried about having them show up in queries.  One option is to just drop rows (from directly within the `sqlite3` interface) up to the current start.

**Comment by jeanconn** [comment]
OK, I'll just figure out the right star time.  This likely stems from the problem that I had no idea what "# The start date might need to be a bit later, e.g. for Manvr use 1999:230 + 21 day" meant in the docs.  Sounds like my start time needs to be a bit later to not get these incomplete-data maneuvers.

**Comment by jeanconn** [comment]
OK, so after changing to "./update_events --start=1999:251", I've got new_db:
```
events.manvrs.filter(start='1999:001', stop='2000:001')
<Manvr: start=1999:231:18:03:14.865 dur=2901 n_dwell=1 template=normal>
<Manvr: start=1999:232:00:00:10.191 dur=789 n_dwell=1 template=normal>
<Manvr: start=1999:232:02:02:39.441 dur=2757 n_dwell=1 template=normal>
<Manvr: start=1999:232:04:37:56.692 dur=240 n_dwell=1 template=normal>
```
And the tests still pass
```
In [5]: paths.EVENTS_DB_PATH()
Out[5]: '/home/jeanconn/git/kadi/events.db3'
In [9]: kadi.test()
============================= test session starts ==============================
platform linux2 -- Python 2.7.9 -- py-1.4.26 -- pytest-2.6.4
collected 15 items 

kadi/tests/test_events.py ..........
kadi/tests/test_occweb.py .....

========================== 15 passed in 46.69 seconds ==========================
Out[9]: 0

```

**Comment by taldcroft** [comment]
Feel free to clarify the kadi docs based on your experience, but otherwise this is good to go.

**Comment by jeanconn** [comment]
OK.  For install process I made a file backup of the current events db and touched the heart_attack

```
cd /proj/sot/ska/data/kadi/ 
cp events.db3 events.db3_pre_one_shot_update
touch task_sched_heart_attack
```
I updated the kadi database in my git repo one more time so it wouldn't lose today's update
```
cd ~/git/kadi
setenv KADI $PWD
python update_events
```
I copied the updated events.db3 into flight
```
cp ~/git/kadi/events.db3 /proj/sot/ska/data/kadi
```
I then updated the kadi module in skare and removed the heart attack.  My preference would be to run the cron job to test (which would also ftp the file to GRETA) but I'm not sure that would work as me anyway.

**Pull request merged**
