### PR TITLE
Use Anaconda as the basis for Ska Python

### PR DESCRIPTION
**Pull request by taldcroft**
This pull request replaces the ancient ActivePython binary Python distribution with [Anaconda](https://store.continuum.io/cshop/anaconda/).  It is not intended for immediate merge, but as a heads-up and platform for discussion.  Ska users should notice no differences.

To do:

- [ ] Review overall infrastructure and confirm it meets our requirements
- [ ] Write infrastructure documentation: 
  - Where things are stored (which are local-only, which go to binstar)
  - What's the relation between ska, ska-flight, ska-ops.  
  - Is `./install.py` entirely eliminated.
- [ ] Create a test document defining procedure and coverage
- [ ] Test using the binstar/CXC sherpa binaries: gui_fit.py and acq_stats fitting (?)
- [ ] Create a procedure document for adding / updating a package
- [ ] Meet with Mark Baski

Pros:
- All of the difficult-to-install packages are already included.
- Many packages that were built from source are now included in the [base install packages](http://docs.continuum.io/anaconda/pkgs.html).
- Includes many new packages that might be quite useful like Mayavi (Vtk-based 3-d rendering) and numba (jit compiled Python).
- Core packages managed with a real package manager `conda`.
- `Conda` can be used to (more) easily create testing environments.
- `Conda` can be used to build binary packages to simplify management of GRETA Ska.
- Base install is available for linux, Windows, Mac.
- This will provide an easier pathway for eventual Python 3 migration.
- Qt4 is currently broken on CentOS-6 (works on CentOS-5 => GRETA).
- Full-featured scientific IDE that brings a Matlab-like experience (spyder).

Cons:
- Disrupts a process that more-or-less works now.
- Will require significant testing and verification on CentOS 5 (32/64 bit) and CentOS-6 (64-bit).
- Will require rework and testing of the GRETA Windows install.
- Drops support for Gtk (linux-only), which requires migrating the Xija fit tool to Qt (partly done).  In principle Gtk could still be provided, but easily not in a cross-platform way.
- Install file is bulky (0.5 Gb).  A lot of that is Qt and Vtk.  In theory it could be trimmed down a bit, but probably not worth the effort.

### CODE REVIEW

**Comment by taldcroft** [comment]
Closed by #46

**Comment by jeanconn** [comment]
I'm not sure if this should be closed; for the pure conda install did we
want to rebase off of this at all?​

**Comment by taldcroft** [comment]
We may pull some commits or ideas from this, but I think that it is so overlapping yet different that we're not going to use this branch (as a whole) in any way.

**Comment by taldcroft** [comment]
Definitely not deleting the branch!

**Pull request closed without merging**
