### PR TITLE
Explicitly unzip python-sybase egg in install

### PR DESCRIPTION
**Pull request by jeanconn**

### CODE REVIEW

**Comment by jeanconn** [comment]
Not sure why this change didn't end up in the config file, but I think we want it.
Or we can just fix this as a hand edit in the new builds.

**Comment by taldcroft** [comment]
What problem is this solving? Have we been testing against a zipped version?

**Comment by jeanconn** [comment]
We have been testing against a zipped verzion.

Current /proj/sot/ska is unzipped and kadi-web doesn't work against a
zipped egg.

**Comment by jeanconn** [comment]
I had this fix in master to keep from breaking kadi-web again.​

**Comment by taldcroft** [comment]
Closed because `skare-0.18` was rebased on master which already had this.

**Pull request closed without merging**
