### PR TITLE
Bring in 2015 leapsec update to C lib and Perl

### PR DESCRIPTION
**Pull request by jeanconn**
Bring in 2015 leapsec update to C lib and Perl

The Chandra::Time package just needed an update for a broken test due to the
new leapsec.

### CODE REVIEW

**Comment by jeanconn** [comment]
So I think this got merged into the rebased 0.18 branch that was then discarded.  Do we want to run with this time update now?  Should anything else be explicitly tested?

**Comment by taldcroft** [comment]
Does `Chandra-Time` have any self tests?  I see you did a simple sanity check on the new leapsec.  I guess this is fine.

**Comment by jeanconn** [comment]
Does Chandra-Time have any self tests? I see you did a simple sanity check
> on the new leapsec. I guess this is fine.
>

Yes.  The self tests were fine except for one I deleted that verified a
date/time in year 2132 that is going to change every time we add a leap
second...

**Comment by taldcroft** [comment]
Hmm, I guess I would have *fixed* the test so as to have a unit test for the most recent leap sec.  Just because a test needs updating occasionally doesn't mean it's a bad thing.

**Comment by jeanconn** [comment]
> Hmm, I guess I would have *fixed* the test so as to have a unit test for
> the most recent leap sec. Just because a test needs updating occasionally
> doesn't mean it's a bad thing
>

Well, I thought the original intent of using a separate XTime library was
so that Chandra-Time would not need an update every time XTime got updated.

**Comment by jeanconn** [comment]
The better fix would probably be to fix our own XTime build so that it
would actually run *those* tests, but I didn't see that as a priority
here.

**Comment by taldcroft** [comment]
From what I see there is no test suite in XTime.  Maybe I'm missing it, or ?  Unless we can see some tests there then an update to XTime should have new tests in Chandra-Time.

**Comment by jeanconn** [comment]
OK.  I did not try to add this test to the XTime package, but I have updated the config to at least run the other tests that are there.  Chandra-Time has been updated to include a test for this leap second in the style of the last test for a leap second:

https://github.com/sot/Chandra-Time/commit/221976b40047943ad60c90dd387e4347b09884bb

**Comment by jeanconn** [comment]
Installed 64 bit with

make xtime
make perl_modules

from unagi.

**Pull request merged**
