### PR TITLE
Add git 2.6.4 via conda

### PR DESCRIPTION
**Pull request by jeanconn**
Add git 2.6.4 via conda

### CODE REVIEW

**Comment by jeanconn** [comment]
I think I built a clean ska with this pkgs.conda, but will recheck.
Also, I did not plan to update git in already-build envs in HEAD ska until we have a driver.

**Comment by jeanconn** [comment]
Oops, kinda need the change in pkgs.conda for this to work.  Looks like that didn't get committed.

**Comment by taldcroft** [comment]
FYI this is a useful post on the back-incompatible change in 2.0:  https://felipec.wordpress.com/2014/05/29/git-v2-0-0/

I think the upshot is that it isn't a problem, though perhaps worth mentioning.  The main thing is `git push` getting more conservative.

**Review by taldcroft — APPROVED** [review]

**Comment by jeanconn** [comment]
I think we don't care about this for skare at this point.

**Pull request closed without merging**
