### PR TITLE
2015 351 models xija update [GRETA-only]

### PR DESCRIPTION
**Pull request by jeanconn**
2015 351 models xija update.  Includes xija with roll and updates to the dpa and acisfp models.  These should go with the 2015_351 matlab tools release.

### CODE REVIEW

**Comment by jeanconn** [comment]
This branch starts from 9b1dae9b2d2d21e2384074229a19fa018aeef0f0 which had been installed on GRETA dev 32b prior to this updates.

**Comment by jeanconn** [comment]
@taldcroft Do the two miniconda 3.19 commits make sense to you here.  My plan is to provide updated "pip freeze" diffs in addition to the pkgs diffs in this case.  I *think* using pkgs.conda to explicitly freeze a couple more of the conda packages makes sense for our purpose, otherwise we get a different version everytime we build (though I'm assuming this behavior will improve with the new 'conda install' once we have the right options in our skare build process).

**Comment by taldcroft** [comment]
This all looks reasonable to me.  :+1: assuming it generates the expected builds.

**Comment by taldcroft** [comment]
The title implies that this will be merged to master at some point, but it seems that this is purely for GRETA and will not be merged.  Is that right?

**Comment by jeanconn** [comment]
Yes.   My original thought was that this could be merged into master, but I think it makes more sense to remove the bracketed text and close this PR unmerged (with the sha fixed and the release archived at https://github.com/sot/skare/releases/tag/0.18-r542-f3fe1d4 ).   We'd then rely on the separate PRs for master ( #77 and #78) to accomplish basically the same things.

**Comment by taldcroft** [comment]
Perfect.

**Pull request closed without merging**
