### PR TITLE
Skare 0.18 - use Anaconda distribution and update most packages to latest stable

### PR DESCRIPTION
**Pull request by taldcroft**
Update python_modules for conda
Use Anaconda 1.9.2 as the basis for Ska Python
Remove pylint and dependencies
Make anaconda cfg work for mac
Remove pyds9
Update .gitignore
Various tweaks for Skare 0.18

### CODE REVIEW

**Comment by taldcroft** [comment]
@jeanconn - this is failing on PDL:
```
t/inlinepdlpp...............Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site
Failed to autogenerate /proj/sot/ska/dev/build/x86_64-linux_CentOS-5/PDL-2.4.4_patch/.inlinepdlpp/config-x86_64-linux-5.008009.

 at t/inlinepdlpp.t line 0
INIT failed--call queue aborted, <DATA> line 1.
# Looks like your test exited with 2 before it could output anything.
t/inlinepdlpp...............dubious                                          
	Test returned status 2 (wstat 512, 0x200)
```

See /pool14/aldcroft/make_all_64.log for the build log.  Maybe I could use some help here.

**Comment by jeanconn** [comment]
I don't know if it matters, but what was in /proj/sot/ska/dev before you tried a make all_64?

**Comment by jeanconn** [comment]
I would guess that the new PDL build is finding an Inline that wasn't
there before and trying to build Inline::Pdlpp  without having
PYTHONHOME.  Maybe prepend the PDL make and make test lines in the cfg
with the

env PYTHONHOME=${prefix_arch}

business?  Or cheat and add inlinepdlpp.t to the list of tests we've
just removed from the build (i.e. gd_oo_tests.t, gis_proj.t,
gsl_interp.t ...).

Do you want me to test this on the side?  I don't know if unagi will
slow down for you if I rebuild up to this point in my own skare and I
don't think you want me writing to /proj/sot/ska/dev just now.

**Comment by taldcroft** [comment]
> I don't know if it matters, but what was in /proj/sot/ska/dev before you tried a make all_64?

Nothing.  At least not in `x86_64_Linux_CentOS-5`.

**Comment by jeanconn** [comment]
Great.  Thanks.

**Comment by taldcroft** [comment]
I'll try your suggestions thanks.

**Comment by taldcroft** [comment]
It seems like something a little funky is happening that might be related to a new setuptools and namespace packages.  Or maybe we never noticed?

In eng_archive/setup.py the first thing that happens is:
```
from Ska.engarchive.version import package_version
```
In the new skare-0.18 this picks up the installed Ska.engarchive if it exists, hence the wrong version.  One has to run `./setup.py install` twice to get things squared up.

Can I say again that using namespace packages ranks as one of the worst mistakes I made.  Basically they don't work and most people don't seem to care.

**Comment by taldcroft** [comment]
Closes #26
Closes #40
Closes #41 
Closes #42

**Comment by taldcroft** [comment]
@jeanconn - do you see any reason not to merge this?

**Comment by jeanconn** [comment]
My only concern is that now the official commit SHA for 0.18 doesn't seem
to match anything in the rebased 0.18 branch.​

**Comment by taldcroft** [comment]
Ack, you've got a point.  Will think.

**Comment by jeanconn** [comment]
​Are we obligated to have the GRETA /proj/sot/ska/dev SHA match the GRETA
/proj/sot/ska SHA ?  Or is it fine if we understand why they are different?

**Comment by taldcroft** [comment]
What is the official SHA?

**Comment by jeanconn** [comment]
I think it is at:

echo '0.18-r460-06aafd2'

​

**Comment by taldcroft** [comment]
I'm going to do a command-line merge of the original skare-0.18 into master.

**Comment by taldcroft** [comment]
OK good, that's what I thought it should be.

**Comment by taldcroft** [comment]
Good catch @jeanconn !  Now we have version 0.18 tagged at 06aafd2 and this skare-0.18 is merged into master!

**Comment by jeanconn** [comment]
:fireworks:​

**Pull request merged**
