### PR TITLE
Bundle small maintenance updates

### PR DESCRIPTION
**Pull request by taldcroft**
### Rationale

These are minor updates to packages that get used in flight operations.

- https://github.com/sot/kadi/pull/113 : Update to allow tests to pass on Mac
- https://github.com/sot/cmd_states/pull/38 : Update to allow tests to pass on Mac
- https://github.com/sot/xija/pull/52 : Add a plot to gui_fit (**does not touch** code that gets run for LR)
- https://github.com/sot/parse_cm/pull/15 : Add functions for writing backstop, DOT, guide summary and updated AOSTRCAT commands for specified obsids.
- https://github.com/sot/eng_archive/pull/149 : regression test values update
- https://github.com/sot/eng_archive/pull/146 : Set fetched bads array to be writeable, needed for remote access

### Testing

All packages pass self-tests on Ska and Ska3.

### Review

Updates were reviewed by @jeanconn or @sot/acis 

### Interface impact

None (apart from a more useful plot in Xija gui_fit)

### Deployment

Install to Ska and Ska3 at any convenient time.

### Backout

This PR can be reverted and prior versions re-installed if necessary.

### CODE REVIEW

**Comment by jeanconn** [comment]
While sot/cmd_states#38 is a change to help tests to pass, the change is not really an "Update to tests" as noted in the PR blurb.

**Comment by jeanconn** [comment]
Also, get_cmd_states is used by starcheck for LR.

**Comment by taldcroft** [comment]
Sigh, good catch.  Was hoping to actually fully complete one thing, but no luck.

**Comment by jeanconn** [comment]
90a5a08 is obviously optional if parse_cm conditionally loads agasc.  I'll revert the change and rebase this on the pycrypto fix so a clean skare2 build on this branch works and has the expected result.

**Comment by jeanconn** [comment]
I've got no idea what the status was on these.

**Comment by taldcroft** [comment]
I think this has all been OBE for Ska2.  I don't see any of these as being ops critical and requiring installation at this point.

**Pull request closed without merging**
