### PR TITLE
Update chandra_aca to 3.14 with centroid residuals

### PR DESCRIPTION
**Pull request by jeanconn**
Update chandra_aca to 3.14 with centroid residuals

### CODE REVIEW

**Comment by jeanconn** [comment]
I didn't use the "-m 1 3c12ac9" option and this seemed to cherry pick fine, but I figured I'd stick it in a pull request to give @taldcroft a veto opportunity.

**Comment by taldcroft** [comment]
I don't want veto opportunity, just do the cherry pick automatically for `py3` if the PR for flight is approved.

**Comment by taldcroft** [comment]
What command did you actually use?

**Comment by jeanconn** [comment]
git cherry-pick 8246c20c14db901c8b8249791a2658904a6529c7

**Comment by jeanconn** [comment]
I figure the pull requests clutter the history but they do at least give me email traceability.

**Comment by taldcroft** [comment]
Yes, but the cherry pick like that won't work for a PR that is more than one commit.  I prefer to not have two PRs for every update to skare.  Even one is more than we used to have, although I see the merit in community visibility for updates.  For the `py3` branch the git history is more than sufficient and better than email.

**Comment by taldcroft** [comment]
Hang  on with installation, chandra_aca 3.14.1 is on its way.

**Comment by taldcroft** [comment]
Closing in favor of standard non-PR process.

**Comment by taldcroft** [comment]
I will do cherry picks.

**Comment by jeanconn** [comment]
Is that "in general" or for getting these changes into py3 today?

**Comment by taldcroft** [comment]
Today.  In general the originator should do the cherry-pick.

**Pull request closed without merging**
