### PR TITLE
Add utility to prune old versions from /proj/sot/ska/pkgs

### PR DESCRIPTION
**Pull request by taldcroft**
This can help a bit with rsyncing packages to other installations.

### CODE REVIEW

**Comment by jeanconn** [comment]
I suppose if you want to install a vintage ska, moving everything back to pkgs from OLD would not be too onerous.

**Comment by taldcroft** [comment]
Exactly.  I did a little more moving of files that I think are no longer used into OLD, but if I messed up then moving back is easy.

**Comment by taldcroft** [comment]
So now I got the active part of `pkgs` down to 400 Mb (from 2.2 Gb).

**Comment by taldcroft** [comment]
And for a vintage install we probably would not want an actual `mv` but rather `ln -s OLD/* .` to make it easy to undo.

**Comment by jeanconn** [comment]
I figured it would be easier to rerun your move script than to do a find and remove on links.

**Pull request merged**
