### PR TITLE
Update starcheck to version 11.23

### PR DESCRIPTION
**Pull request by jeanconn**
Include accompanying changes to hopper (0.3) and Chandra.Maneuver (3.7)

### CODE REVIEW

**Comment by taldcroft** [comment]
Please use an individual commit for each package update so there is visibility in the commit log.

**Comment by taldcroft** [comment]
Also, Ska flight still has Chandra.Maneuver 3.6.

**Comment by jeanconn** [comment]
Do you want to rebase this with individual commits or is that a direction for future PRs?

**Comment by taldcroft** [comment]
Future PRs.  We *never* rebase master.

**Comment by jeanconn** [comment]
Also, Gah.  Sorry I tested that starcheck and ska_testr worked but must have forgotten to test version explicitly on Chandra.Maneuver.  I'm assuming that it didn't install because it passed tests and had a .installed file.  Forgot about that when I ran the update.

**Comment by jeanconn** [comment]
Should probably also lock master on skare then too, right?

**Comment by jeanconn** [comment]
Also, I'll get the Chandra.Maneuver update on flight now and will retest.  Thanks for the catch!

**Comment by jeanconn** [comment]
I've also updated my in-work install doc with a note for each environment to take the time to explicitly check that the installed version is expected.  And I'll take an action to see if there is a nice way to update / extend the package_manifest test in ska_testr to confirm that the packages in pkgs.manifest are the ones that are actually installed.

**Pull request merged**
